### ISSUE TITLE
failure with one-word sentence

### ISSUE THREAD

**Issue by nicolabertoldi** [aaronlifenghan/aaron-project-hlepor#2]
the code fails when source (and ref) contains just one word

with this error
```
Use of uninitialized value in string eq at .... line 227
```
It seems that at this line
https://github.com/aaronlifenghan/aaron-project-hlepor/blob/992d182fc4a0c254fd06e172761204bd7f1d9d39/source%20code#L227

the array is queried for the second position even if just the text contains just one word.

**Comment by poethan** [comment]
It shall be ok with one word sentence.

**Comment by poethan** [comment]
here is the ongoing maintaining version https://github.com/poethan/LEPOR including hLEPOR

**Comment by nicolabertoldi** [comment]
Actually the score is computed; maybe they are only warnings.
But I am not sure if it is correct

I tried to compare with score returned by the Inten.to API and there is a difference

In my toy case, your tool returns    0.5,
while Inten.to PIA returns 0.508832387099159

Not sure if only a matter of precision;
Is it possible to increase the precision in your software?

**Comment by nicolabertoldi** [comment]
I will try with the version you pointed.


I would suggest to make filenames parametric

**Comment by poethan** [comment]
that is good suggestion. I was planning to package the tool and make it easier for users. I used to have chats with some users including skype call for how to use it. :)

**Comment by nicolabertoldi** [comment]
I opened a new issue on the other version
which seems the one you are maintaining.

**Comment by nicolabertoldi** [comment]
thanks for the offer of a chat
maybe next week
